secret:
  key: SVRTX1NFQ1JFVF9LRVlfRk9SX0FQUExJQ0FUSU9OX01ZX01JQ1JPc2VydmljZV9jbG91ZF9hcHBfcmVwb3NpeW9yaXk=
expired:
  time: 600
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    password: postgres
    username: postgres
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
